# mappings.py

# Tournament name mapping
tournament_name_mapping = {
    "French Open": "Roland Garros",
    "BNP Paribas Open": "Indian Wells Masters",
    "Western & Southern Financial Group Masters": "Cincinnati Masters",
    "Mutua Madrid Open": "Madrid Masters",
    "Geneva Open": "Geneva",
    "Lyon Open": "Lyon",
    "Sony Ericsson Open": "Miami Masters",
    "Heineken Open": "Auckland",
    "Masters Cup": "Tour Finals",
    "Winston-Salem Open at Wake Forest University": "Winston-Salem",
    "AEGON Championships": "Queen's Club",
    "AnyTech365 Andalucia Open": "Marbella"
}

# Player name mapping
atp_player_name_mapping = {
    "Dutra Silva R.": "Rogerio Dutra Silva",
    "Mcdonald M.": "Mackenzie Mcdonald",
    "Mackenzie McDonald": "Mackenzie Mcdonald",
    "Albot R.": "Radu Albot",
    "Auger-Aliassime F.": "Felix Auger Aliassime",
    "Bagnis F.": "Facundo Bagnis",
    "Baez S.": "Sebastian Baez",
    "Djere L.": "Laslo Djere",
    "Etcheverry T.": "Tomas Martin Etcheverry",
    "Carballes Baena R.": "Roberto Carballes Baena",
    "Menendez-Maceiras A.": "Adrian Menendez Maceiras",
    "Van De Zandschulp B.": "Botic Van De Zandschulp",
    "Botic Van De Zandschul": "Botic Van De Zandschulp",
    "B Van de Zandschulp": "Botic Van De Zandschulp",
    "Botic Van de Zandschulp": "Botic Van De Zandschulp",
    "Ramos-Vinolas A.": "Albert Ramos",
    "Carreno-Busta P.": "Pablo Carreno Busta",
    "Carreno Busta P.": "Pablo Carreno Busta",
    "Bautista Agut R.": "Roberto Bautista Agut",
    "O Connell C.": "Christopher Oconnell",
    "Christopher O'Connell": "Christopher Oconnell",
    "Christopher O Connell": "Christopher Oconnell",
    "De Minaur A.": "Alex De Minaur",
    "Zapata Miralles B.": "Bernabe Zapata Miralles",
    "Davidovich Fokina A.": "Alejandro Davidovich Fokina",
    "Del Potro J.M.": "Juan Martin del Potro",
    "Gomez A.": "Alejandro Gomez",
    "Alejandro Gomez Gb42": "Alejandro Gomez",
    "Roca Batalla O.": "Oriol Roca Batalla",
    "Lopez San Martin A.": "Alvaro Lopez San Martin",
    "Garcia-Lopez G.": "Guillermo Garcia Lopez",
    "Munoz De La Nava D.": "Daniel Munoz de la Nava",
    "Vilella Martinez M.": "Mario Vilella Martinez",
    "Llamas Ruiz P.": "Pablo Llamas Ruiz",
    "De Schepper K.": "Kenny De Schepper",
    "De Bakker T.": "Thiemo De Bakker",
    "Seyboth Wild T.": "Thiago Seyboth Wild",
    "Kuznetsov An.": "Andrey Kuznetsov",
    "Nava E.": "Emilio Nava",
    "Haider-Maurer A.": "Andreas Haider Maurer",
    "Basilashvili N.": "Nikoloz Basilashvili",
    # betfair relevant mappings below
    "Yunchaokete Bu": "Bu Yunchaokete",
    "B Yunchaokete": "Bu Yunchaokete",
    "Pierre-Hugues Herbert": "Pierre Hugues Herbert",
    "Jan-Lennard Struff": "Jan Lennard Struff",
    "Felix Auger-Aliassime": "Felix Auger Aliassime",
    "Giovanni Mpetshi Perricard": "Giovanni Mpetshi Perricard",
    "Giovanni Mpetshi Perric": "Giovanni Mpetshi Perricard",
    "G Mpetshi Perricard": "Giovanni Mpetshi Perricard",
    "J.j. Wolf": "J J Wolf",
    "Jeffrey John Wolf": "J J Wolf",
    "John Jeffrey Wolf": "J J Wolf",
    "Alejandro Fokina": "Alejandro Davidovich Fokina",
    "A Davidovich Fokina": "Alejandro Davidovich Fokina",
    "Marc-Andrea Huesler": "Marc Andrea Huesler",
    "Soonwoo Kwon": "Soon Woo Kwon",
    "Chun-Hsin Tseng": "Chun Hsin Tseng",
    "Seongchan Hong": "Seong Chan Hong",
    "Manuel Cerundolo": "Juan Manuel Cerundolo",
    "Albert Ramos-Vinolas": "Albert Ramos",
    "Albert Ramos Vinolas": "Albert Ramos",
    "M  Ymer": "Mikael Ymer",
    "D  Evans": "Daniel Evans",
    "Daniel  Evans": "Daniel Evans",
    "Moreno De Alboran": "Nicolas Moreno De Alboran",
    "Nicolas Moreno De Albor": "Nicolas Moreno De Alboran",
    "Marcelo Tomas Barrios Vera": "Tomas Barrios Vera",
    "Tomas M Etcheverry": "Tomas Martin Etcheverry",
    "Felxi Auger-Aliassime": "Felix Auger Aliassime",
    "F Auger Aliassime": "Felix Auger Aliassime",
    "Abdullah Shelbayh": "Abedallah Shelbayh",
    "Tung-Lin Wu": "Tung Lin Wu",
    "Holger Vitus Nodskov Ru": "Holger Rune",
    "Holger Vitus Nodskov Rune": "Holger Rune",
    "Alejandro Davidovich Fo": "Alejandro Davidovich Fokina",
    "Carballes Baena": "Roberto Carballes Baena",
    "Cedrik-Marcel Stebe": "Cedrik Marcel Stebe",
    "Christian Garin": "Cristian Garin",
    "Guillermo Garcia-Lopez": "Guillermo Garcia Lopez",
    "D Stricker": "Dominic Stricker",
    "Jo Wilfried Tsonga": "Jo-Wilfried Tsonga",
    "Victor Estrella Burgos": "Victor Estrella",
    "Yen-Hsun Lu": "Yen Hsun Lu",
    "Paul-Henri Mathieu": "Paul Henri Mathieu",
    "Dominic Stephan Stricke": "Dominic Stricker",
    "Adrian Menendez-Maceira": "Adrian Menendez Maceiras",
    "Adrian Menendez Maceira": "Adrian Menendez Maceiras",
    "Inigo Cervantes": "Inigo Cervantes Huegun",
    "I Cervantes Huegun": "Inigo Cervantes Huegun",
    "Daniel Gimeno-Traver": "Daniel Gimeno Traver",
    "T Daniel": "Taro Daniel",
    "Daniel Taro": "Taro Daniel",
    "J Londero": "Juan Ignacio Londero",
    "A Popyrin": "Alexei Popyrin",
    "J De Jong": "Jesper De Jong",
    "G Barrere": "Gregoire Barrere",
    "L Sonego": "Lorenzo Sonego",
    "M Kecmanovic": "Miomir Kecmanovic",
    "S Baez": "Sebastian Baez",
    "A Michelsen": "Alex Michelsen",
    "F Tiafoe": "Frances Tiafoe",
    "Francis Tiafoe": "Frances Tiafoe",
    "R Bautista-Agut": "Roberto Bautista Agut",
    "Matt Arnaldi": "Matteo Arnaldi",
    "M Berrettini": "Matteo Berrettini",
    "F Comesana": "Francisco Comesana",
    "F Fognini": "Fabio Fognini",
    "Fognini, Fabio": "Fabio Fognini",
    "R Safiullin": "Roman Safiullin",
    "D Lajovic": "Dusan Lajovic",
    "H Medjedovic": "Hamad Medjedovic",
    "D Altmaier": "Daniel Altmaier",
    "T Seyboth Wild": "Thiago Seyboth Wild",
    "De Minaur, Alex": "Alex De Minaur",
    "A De Minaur": "Alex De Minaur",
    "De Minaur": "Alex De Minaur",
    "C Garin": "Cristian Garin",
    "Garin, Cristian": "Cristian Garin",
    "Diego Sebastian Schwartzman": "Diego Schwartzman",
    "D Schwartzman": "Diego Schwartzman",
    "Schwartzman, Diego": "Diego Schwartzman",
    "Struff, Jan-Lennard": "Jan Lennard Struff",
    "R Nadal": "Rafael Nadal",
    "A Shevchenko": "Alexander Shevchenko",
    "Zapata Miralles": "Bernabe Zapata Miralles",
    "Luca Assche Van": "Luca Van Assche",
    "L Van Assche": "Luca Van Assche",
    "Elahi Daniel Galan": "Daniel Elahi Galan",
    "D Galan": "Daniel Elahi Galan",
    "R Hijikata": "Rinky Hijikata",
    "Pablo Juan Varillas": "Juan Pablo Varillas",
    "J Varillas": "Juan Pablo Varillas",
    "Thai-Son Kwiatkowski": "Thai Son Kwiatkowski",
    "T Kwiatkowski": "Thai Son Kwiatkowski",
    "J Manuel Cerundolo": "Juan Manuel Cerundolo",
    "J Cerundolo": "Juan Manuel Cerundolo",
    "F Cerundolo": "Francisco Cerundolo",
    "D Medvedev": "Daniil Medvedev",
    "Taylor Harry Fritz": "Taylor Fritz",
    "T Fritz": "Taylor Fritz",
    "Fritz, Taylor": "Taylor Fritz",
    "G Dimitrov": "Grigor Dimitrov",
    "D Thiem": "Dominic Thiem",
    "Alexander Zverev ": "Alexander Zverev",
    "A Zverev": "Alexander Zverev",
    "M Zverev": "Mischa Zverev",
    "S Johnson": "Steve Johnson",
    "T Paul": "Tommy Paul",
    "D Goffin": "David Goffin",
    "S Tsitsipas": "Stefanos Tsitsipas",
    "N Djokovic": "Novak Djokovic",
    "N Djokovic": "Novak Djokovic",
    "Djokovic, Novak": "Novak Djokovic",
    "S Querrey": "Sam Querrey",
    "2. Sam Querrey": "Sam Querrey",
    "T Sandgren": "Tennys Sandgren",
    "R Gasquet": "Richard Gasquet",
    "P Sousa": "Pedro Sousa",
    "J Sousa": "Joao Sousa",
    "J Sock": "Jack Sock",
    "N Basilashvili": "Nikoloz Basilashvili",
    "R Carballes Baena": "Roberto Carballes Baena",
    "T Kamke": "Tobias Kamke",
    "H Hurkacz": "Hubert Hurkacz",
    "Hurkacz": "Hubert Hurkacz",
    "C Ruud": "Casper Ruud",
    "R Opelka": "Reilly Opelka"
}

# List of players who should not have their last name extracted
atp_players_no_last_name_extraction = set(atp_player_name_mapping.values())
