# Tournament to country mapping (IOC codes)
atp_tournament_country_mapping = {
    "ABN AMRO World Tennis Tournament": "NED",
    "AEGON Championships": "GBR",
    "AEGON International": "GBR",
    "AEGON Open": "GBR",
    "ASB Classic": "NZL",
    "Abierto Mexicano": "MEX",
    "Abierto Mexicano Mifel": "MEX",
    "Adelaide International": "AUS",
    "Adelaide International 1": "AUS",
    "Adelaide International 2": "AUS",
    "Almaty Open": "KAZ",
    "Antalya Open": "TUR",
    "AnyTech365 Andalucia Open": "ESP",
    "Apia International": "AUS",
    "Argentina Open": "ARG",
    "Astana Open": "KAZ",
    "Atlanta Open": "USA",
    "Australian Open": "AUS",
    "BB&T Atlanta Open": "USA",
    "BMW Open": "GER",
    "BNP Paribas Masters": "FRA",
    "BNP Paribas Open": "USA",
    "BRD Nastase Tiriac Trophy": "ROU",
    "Barcelona Open": "ESP",
    "Belgrade Open": "SRB",
    "Brasil Open": "BRA",
    "Brisbane International": "AUS",
    "Canadian Open": "CAN",
    "Chengdu Open": "CHN",
    "Chennai Open": "IND",
    "Chile Open": "CHI",
    "China Open": "CHN",
    "Citi Open": "USA",
    "Claro Open Colombia": "COL",
    "Cordoba Open": "ARG",
    "Croatia Open": "CRO",
    "Dallas Open": "USA",
    "Delray Beach Open": "USA",
    "Dubai Tennis Championships": "UAE",
    "Eastbourne International": "GBR",
    "Ecuador Open": "ECU",
    "Emilia-Romagna Open": "ITA",
    "Erste Bank Open": "AUT",
    "Estoril Open": "POR",
    "European Open": "BEL",
    "Firenze Open": "ITA",
    "Forte Village Sardegna Open": "ITA",
    "French Open": "FRA",
    "Garanti Koza Sofia Open": "BUL",
    "Gazprom Hungarian Open": "HUN",
    "Generali Open": "AUT",
    "Geneva Open": "SUI",
    "German Tennis Championships": "GER",
    "Gerry Weber Open": "GER",
    "Gijon Open": "ESP",
    "Grand Prix Hassan II": "MAR",
    "Great Ocean Road Open": "AUS",
    "Hall of Fame Championships": "USA",
    "Halle Open": "GER",
    "Hangzhou Open": "CHN",
    "Heineken Open": "NZL",
    "Hong Kong Tennis Open": "HKG",
    "Hungarian Open": "HUN",
    "Internazionali BNL d'Italia": "ITA",
    "Istanbul Open": "TUR",
    "Japan Open Tennis Championships": "JPN",
    "Konzum Croatia Open": "CRO",
    "Korea Open": "KOR",
    "Kremlin Cup": "RUS",
    "Los Cabos Open": "MEX",
    "Lyon Open": "FRA",
    "Maharashtra Open": "IND",
    "Malaysian Open": "MAS",
    "Mallorca Championships": "ESP",
    "Masters Cup": "CHN",
    "Melbourne Summer Set": "AUS",
    "Memphis Open": "USA",
    "Mercedes Cup": "GER",
    "Miami Open": "USA",
    "Mifel Open": "MEX",
    "Millenium Estoril Open": "POR",
    "Millennium Estoril Open": "POR",
    "Monte Carlo Masters": "MON",
    "Murray River Open": "AUS",
    "Mutua Madrid Open": "ESP",
    "Napoli Cup": "ITA",
    "New York Open": "USA",
    "Nordea Open": "SWE",
    "Nordic Open": "SWE",
    "Open 13": "FRA",
    "Open Banco Sabadell": "ESP",
    "Open Sud de France": "FRA",
    "Open de Moselle": "FRA",
    "Open de Nice Côte d’Azur": "FRA",
    "PBZ Zagreb Indoors": "CRO",
    "Qatar Exxon Mobil Open": "QAT",
    "Queen's Club Championships": "GBR",
    "Rakuten Japan Open Tennis Championships": "JPN",
    "Ricoh Open": "NED",
    "Rio Open": "BRA",
    "Rogers Masters": "CAN",
    "Rosmalen Grass Court Championships": "NED",
    "San Diego Open": "USA",
    "Sardegna Open": "ITA",
    "Serbia Open": "SRB",
    "Shanghai Masters": "CHN",
    "Shenzhen Open": "CHN",
    "Singapore Open": "SGP",
    "SkiStar Swedish Open": "SWE",
    "Sofia Open": "BUL",
    "Sony Ericsson Open": "USA",
    "Srpska Open": "BIH",
    "St. Petersburg Open": "RUS",
    "Stockholm Open": "SWE",
    "Stuttgart Open": "GER",
    "Suisse Open Gstaad": "SUI",
    "Swiss Indoors": "SUI",
    "Sydney International": "AUS",
    "Sydney Tennis Classic": "AUS",
    "Tata Open": "IND",
    "Tel Aviv Open": "ISR",
    "Tiriac Open": "ROU",
    "Topshelf Open": "NED",
    "U.S. Men's Clay Court Championships": "USA",
    "US Open": "USA",
    "Valencia Open 500": "ESP",
    "Vienna Open": "AUT",
    "Viking International": "GBR",
    "Western & Southern Financial Group Masters": "USA",
    "Wimbledon": "GBR",
    "Winston-Salem Open at Wake Forest University": "USA",
    "Zhuhai Championships": "CHN",
    "Zhuhai Open": "CHN",
    "bet-at-home Open": "GER",
    "bett1HULKS Championship": "GER",
    "bett1HULKS Indoors": "GER"
}

# WTA Tournament to IOC Country Mapping
wta_tournament_country_mapping = {
    "AEGON Classic": "GBR",
    "AEGON International": "GBR",
    "ASB Classic": "NZL",
    "ATX Open": "USA",
    "Abierto Mexicano": "MEX",
    "Abierto Zapopan": "MEX",
    "Abu Dhabi WTA Women's Tennis Open": "UAE",
    "Adelaide International": "AUS",
    "Adelaide International 1": "AUS",
    "Adelaide International 2": "AUS",
    "Aegon Open": "GBR",
    "Apai International": "AUS",
    "Astana Open": "KAZ",
    "Australian Open": "AUS",
    "BGL BNP Paribas Luxembourg Open": "LUX",
    "BNP Paribas Fortis Diamond Games": "BEL",
    "BNP Paribas Open": "USA",
    "BNP Paribas WTA Finals": "SGP",
    "Bad Homburg Open": "GER",
    "Baku Cup": "AZE",
    "Baltic Open": "LAT",
    "Bank of the West Classic": "USA",
    "Bett1Open": "GER",
    "Birmingham Classic": "GBR",
    "Brasil Tennis Cup": "BRA",
    "Brisbane International": "AUS",
    "Bronx Open": "USA",
    "Bucharest Open": "ROU",
    "Budapest Open": "HUN",
    "Canadian Open": "CAN",
    "Championnats de Granby": "CAN",
    "Charleston Open": "USA",
    "Chennai Open": "IND",
    "Chicago Fall Tennis Classic": "USA",
    "Chicago Women's Open": "USA",
    "China Open": "CHN",
    "Citi Open": "USA",
    "Collector Swedish Open": "SWE",
    "Connecticut Open": "USA",
    "Copa Claro Colsanitas": "COL",
    "Copa Colsanitas": "COL",
    "Coupe Banque Nationale": "CAN",
    "Courmayeur Ladies Open": "ITA",
    "Dubai Duty Free Tennis Championships": "UAE",
    "Eastbourne International": "GBR",
    "Emilia-Romagna Open": "ITA",
    "Ericsson Open": "SWE",
    "European Open": "BEL",
    "Family Circle Cup": "USA",
    "French Open": "FRA",
    "Gastein Ladies": "AUT",
    "Generali Ladies Linz": "AUT",
    "Generali Ladies Linz Open": "AUT",
    "German Open": "GER",
    "Gippsland Trophy": "AUS",
    "Grampians Trophy": "AUS",
    "Grand Prix SAR Lalla Meryem": "MAR",
    "Guadalajara Open": "MEX",
    "Guangzhou Open": "CHN",
    "Hobart International": "AUS",
    "Hong Kong Tennis Open": "HKG",
    "Hungarian Ladies Open": "HUN",
    "Iasi Open": "ROU",
    "Internationaux de Strasbourg": "FRA",
    "Internazionali BNL d'Italia": "ITA",
    "Internazionali Femminili di Palermo": "ITA",
    "Istanbul Cup": "TUR",
    "J&T Banka Prague Open": "CZE",
    "Japan Open": "JPN",
    "Japan Women's Tennis Open": "JPN",
    "Jasmin Open": "TUN",
    "Jiangxi Open": "CHN",
    "Jiangxi Tennis Open": "CHN",
    "Jiangxi Women's Tennis Open": "CHN",
    "Katowice Open": "POL",
    "Kia Korea Open": "KOR",
    "Korea Open": "KOR",
    "Kremlin Cup": "RUS",
    "Ladies Championship Gstaad": "SUI",
    "Ladies Linz Open": "AUT",
    "Ladies Open Biel Bienne": "SUI",
    "Ladies Open Lausanne": "SUI",
    "Ladies Trophy": "RUS",
    "Luxembourg Open": "LUX",
    "Lyon Open": "FRA",
    "MUSC Health Women's Open": "USA",
    "Malaysia Open": "MAS",
    "Mallorca Open": "ESP",
    "Melbourne Summer Set 1": "AUS",
    "Melbourne Summer Set 2": "AUS",
    "Merida Open": "MEX",
    "Miami Open": "USA",
    "Monterrey Open": "MEX",
    "Morocco Open": "MAR",
    "Moscow River Cup": "RUS",
    "Mubadala Silicon Valley Classic": "USA",
    "Mutua Madrid Open": "ESP",
    "Ningbo Open": "CHN",
    "Nottingham Open": "GBR",
    "Nürnberger Versicherungscup": "GER",
    "Open de Rouen": "FRA",
    "Ostrava Open": "CZE",
    "Parma Ladies Open": "ITA",
    "Pattaya Women's Open": "THA",
    "Phillip Island Trophy": "AUS",
    "Poland Open": "POL",
    "Porsche Tennis Grand Prix": "GER",
    "Prague Open": "CZE",
    "Prudential Hong Kong Tennis Open": "HKG",
    "Qatar Open": "QAT",
    "Qatar Total Open": "QAT",
    "Ricoh Open": "NED",
    "Rio Open": "BRA",
    "Rogers Cup": "CAN",
    "Rosmalen Grass Court Championships": "NED",
    "Rothesay Classic": "GBR",
    "Rothesay International": "GBR",
    "Samsung Open": "SUI",
    "San Diego Open": "USA",
    "Serbia Ladies Open": "SRB",
    "Shenzhen Open": "CHN",
    "Slovenia Open": "SLO",
    "Sony Ericsson Championships": "USA",
    "Sony Ericsson Open": "USA",
    "Sydney International": "AUS",
    "Sydney Tennis Classic": "AUS",
    "TEB BNP Paribas Istanbul Cup": "TUR",
    "Taiwan Open": "TPE",
    "Tallinn Open": "EST",
    "Tashkent Open": "UZB",
    "Tenerife Ladies Open": "ESP",
    "Tennis in the Land": "USA",
    "Thailand Open": "THA",
    "Thailand Open 2": "THA",
    "Tianjin Open": "CHN",
    "Top Seed Open": "USA",
    "Topshelf Open": "NED",
    "Toray Pan Pacific Open": "JPN",
    "Toray Pan Pacific Open Tennis Tournament": "JPN",
    "Transylvania Open": "ROU",
    "US Open": "USA",
    "Viking Classic": "GBR",
    "Viking International": "GBR",
    "Volvo Car Open": "USA",
    "WTA Elite Trophy": "CHN",
    "WTA Finals": "CHN",
    "Western & Southern Financial Group Women's Open": "USA",
    "Wimbledon": "GBR",
    "Wuhan Open": "CHN",
    "Yarra Valley Classic": "AUS",
    "Zhengzhou Open": "CHN",
}

